sudo: false
language: node_js
node_js:
  - '0.10'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm config set spin false --global
after_script:
  - ./scripts/bower-deploy.sh
deploy:
  provider: npm
  email: oss@ehealthafrica.org
  skip_cleanup: true
  on:
    branch: master
    repo: eHealthAfrica/qsl.js
  api_key:
    secure: jH7/dWbQNtdO0M7wvyzpCCEQe0IUEo4YwIf/34kvdRAHNUDjmxcGFNfU0UlIk5PXWAvLsDld3XSk+SJKHzkofaH7itTRYkNJw+MkyCm9v7IaqeBB0Qw4TQ1BDkSnf5q6UjV8tHXWZLnGb09ad10D0FxhbXmExPvuq39StORLIKDKr5nbqxm9xq3P5AaCOcliHtvNxVS2f+2WYkbEVhIvXiYg3qKasMKeVBGshjsafO3vTFnnAYilTLEO3JIVJrkrHhnjGGx+EOVBroxHEB+l51exLcmnXE8WTXJQyKLPV3jwllEMr/p4O8GIoULIDiZ/v06ziAbQq4/L6uDzqW/OqcKiNSdqzyDtUsK5CDBSpv+aBNWpPeKtzPRIufgu52AjOZYdEoxGTZaOtwMwLcxZ8mvEf+YS84oAwUjaxmUmlTxfLTkHV9QQ2zOw56x1DVLRDedbwTEDGz/U4PNGLZb3xFV59EvxMKVTvBy5nZ+IvsP7r2itZ9jwQA5cYjEDxqPdnPOn/n+ankfxlqUeKdOYtNl9rxbB+m8ks9EbrdlVJJGWwdSr13G3tJoZZceV4oBa6glCEhehyrBtHB0Ae1ofJkuwsQiZtw2AQPyp5To7bILpXLz4nBgUH5C8R3uFnr+8pX3fvZGSfhQJTK+WZBpwt1RpaRwJsMDNSjc1GlNo3H4=
env:
  global:
    secure: EAxdsOha3E8kBTYHxF9kUjRm/CF5g+jgazfT5zIa3oItRcFgapq0Y6u3iYsnEbkF24Ds5s+bl1NgtL4tyzxD6kC2obM0f7U+nfhgJRwS+Vm4uWP1rXEIh2SqTZXsA3a6XemgTr1w0N/L/AuSswmT+0bgjCAbHNqH9MXZ35us0kSZXd+F8FYI4+BipNyjBMBdRMyGpwCHN/5Yaogtvs21/AKG7RJeQ5ZkGcfVz1fGZqz4kMGqVNmGLQER4u+tX81ZrFyDV0Bu9kciLyaOTxd2XGwzE2ttRIgDipPcDaeZy875uNvZaVwlTqhOMY8b1aZwLMPp/gPiP6O+3sBcwpr/UmMuO87JU7KIeJeXVHn3J9FxBhehcAh7QJH7ku2eX0jmKzYCzovg0I8/1UgDsNUQkSLoyz+YS5awvaC07vewk03IEG/J5uZ0ELKuq6XUEDA9lNLLnYVdsWI6TiBs5BJJwtpmOvkOtL0sCGY1eXau5uzPQaPyBHXLwK7rLpO0/WQz9r3BVz7O4/TNJ0HsElBikvjHE19HcC7KsBtacWslnS9C98i0FtbQPbDOnUZVwKKrzaKCtW/Q++RAionwdhwP4DoH5+BrO0Yz3NOC0fyxb6MNEoLZZN/qd/TZHwh+2IXnZXnRZGQTUsukcLKBjZqOHPoQ/N2QccdFrYze/9U1kZg=
